# Generated by Django 5.2.4 on 2025-07-21 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_grade',
            field=models.IntegerField(choices=[(1, '1. Sınıf'), (2, '2. Sınıf'), (3, '3. Sınıf'), (4, '4. Sınıf'), (5, '5. Sınıf'), (6, '6. Sınıf')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
