# Generated by Django 5.2.4 on 2025-07-21 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_alter_announcement_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_type',
            field=models.CharField(choices=[('university', 'Üniversite Duyurusu'), ('faculty', 'Fakülte Duyurusu'), ('department', 'Bölüm Duyurusu')], max_length=15),
        ),
    ]
