# Generated by Django 4.2.28 on 2026-02-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_credits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcourse',
            name='semester',
            field=models.CharField(choices=[('fall', 'Güz'), ('spring', 'Bahar'), ('summer', 'Yaz')], max_length=10),
        ),
    ]
