# Generated by Django 5.2.4 on 2025-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='country',
            field=models.CharField(default='Turkiye', max_length=100),
        ),
    ]
